//THIS IS A CLASS FOR TYPE OF WORDS WHICH DON'T HAVE A DIRECT CD FORM REPRESENTATION IN THE BASIC ACTIONS BUT ARE EXPRESSED AS " THE ACTOR DOING SOMETHING THAT RESULTS IN SOMETHING HAPPENING".
//EG, KILL IS ACTOR DOING SOMETHING THAT RESULTS IN THE OBJECT'S HEALTH BECOMING -10 = DEAD.
//DO_SOMETHING1 TYPE OF VERBS WHERE THE OBJECT ON WHICH THE ACTOR ACTS IS OF TYPE ACTOR. ACCORDINGLY THE STATES OF THE OBJECT ARE CHANGED.
public class do_something1 extends action {
	Actor_Place_structure actor = new Actor_Place_structure(); //ACTOR OF THE ACTION
	Actor_Place_structure object = new Actor_Place_structure(); //OBJECT BEING ACTED UPON. IT IS OF TYPE PERSON OR PLACE HERE.
	IObject_structure using_instrument = new IObject_structure(); //USING WHAT INSTRUCMENT IS THE ACTION BEING CONDUCTED.
	/*
	 * CD-FORM
	 * (DO SOMETHING
		(ACTOR VAR1)
		(OBJECT VAR2)
		(CONC_TENSE VAR3)
		(USING VAR4)
    	(ADVERB VAR5)
		)
	 */

}
